- name: Create SSH Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: Write SSH Private Key
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    content: "{{ ssh_priv_key }}"
    mode: '0600'

- name: Write SSH Public Key
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    content: "{{ ssh_pub_key }}"
    mode: "0644"

- name: Set Authorized Keys
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ ssh_pub_key }}"
