- hosts: localhost
  gather_facts: true
  vars:
    remote: false
    user: "{{ ansible_facts.env.USER }}"
  vars_files:
    - config.yaml
    - secrets.yaml
  roles:
    - system
    - dev
    - editor
    - terminal
    - secrets
