# non-Neovim rocks.
[rocks]

# Neovim plugins
[plugins]
"conform.nvim" = "9.1.0"
"gitsigns.nvim" = "1.0.2"
"lsp_signature.nvim" = "0.3.1"
"lualine.nvim" = "scm"
"mason-lspconfig.nvim" = "2.1.0"
"mason.nvim" = "2.1.0"
"mini.bufremove" = "0.16.0"
"mini.comment" = "0.16.0"
"plenary.nvim" = "scm"
"rocks-git.nvim" = "2.5.6"
"rocks-treesitter.nvim" = "1.3.1"
"rocks.nvim" = "2.46.1"
"telescope.nvim" = "scm"
nvim-web-devicons = "0.100"
tree-sitter-go = "0.0.39"
tree-sitter-toml = "0.0.31"
tree-sitter-yaml = "0.0.36"
tree-sitter-starlark = "0.0.31"
tree-sitter-gomod = "0.0.34"
tree-sitter-gosum = "0.0.30"
tree-sitter-typescript = "0.0.37"
tree-sitter-make = "0.0.30"
tree-sitter-jinja = "0.0.8"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-json = "0.0.36"
tree-sitter-git_config = "0.0.31"
tree-sitter-javascript = "0.0.37"
tree-sitter-rust = "0.0.50"
tree-sitter-capnp = "0.0.29"
tree-sitter-proto = "0.0.29"
tree-sitter-python = "0.0.46"
tree-sitter-hcl = "0.0.34"
tree-sitter-cpp = "0.0.45"
tree-sitter-ini = "0.0.32"
neogit = "3.0.0"

[plugins.nvim]
git = "catppuccin/nvim"
rev = "v1.11.0"

[plugins.coq]
git = "ms-jpq/coq_nvim"
rev = "coq"

[plugins."coq.artifacts"]
git = "ms-jpq/coq.artifacts"
rev = "artifacts"

[plugins.telescope-zoxide]
git = "jvgrootveld/telescope-zoxide"
rev = "v2.1"

# Treesitter syntaxes
[treesitter]
auto_highlight = [
  "comment",
  "c",
  "capnp",
  "cpp",
  "dockerfile",
  "editorconfig",
  "fish",
  "git_config",
  "git_rebase",
  "gitattributes",
  "gitcommit",
  "gitignore",
  "go",
  "gomod",
  "gosum",
  "gotmpl",
  "gowork",
  "hcl",
  "http",
  "ini",
  "javascript",
  "jinja",
  "jinja_inline",
  "json",
  "json5",
  "jsonc",
  "kconfig",
  "lua",
  "make",
  "meson",
  "ninja",
  "passwd",
  "perl",
  "printf",
  "promql",
  "proto",
  "puppet",
  "python",
  "regex",
  "requirements",
  "rst",
  "rust",
  "sql",
  "ssh_config",
  "starlark",
  "strace",
  "terraform",
  "toml",
  "typescript",
  "typst",
  "udev",
  "vim",
  "vimdoc",
  "xml",
  "yaml",
]
auto_install = true
