# vim: ft=yaml.ansible
---
- name: Install Base System Tools
  ansible.builtin.apt:
    name:
      - curl
      - jq
      - openssh-client
      - sudo
      - yq
    state: present
  become: true

- name: Current User Can sudo Without Password
  ansible.builtin.template:
    src: "{{ role_path }}/files/sudo_user_nopasswd.jinja"
    dest: "/etc/sudoers.d/{{ user }}_nopasswd"
    validate: /usr/sbin/visudo -cf %s
    mode: '0660'
  become: true

- name: Create Systemd User Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory

- name: Create Systemd Environment Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.environment.d"
    state: directory
  when: not remote
