- name: Install Terminal Utilities
  ansible.builtin.apt:
    name:
      - bat
      - ripgrep
      - fd-find
      - btop
    state: latest
  become: true

- name: Include Fish Tasks
  ansible.builtin.include_tasks: "./fish.yaml"

- name: Include Tmux Tasks
  ansible.builtin.include_tasks: "./tmux.yaml"

- name: Include Kitty Tasks
  ansible.builtin.include_tasks: "./kitty.yaml"
