#!/usr/bin/env bash

# Credit for this script goes to meskarune (https://github.com/meskarune/i3lock-fancy)

set -o errexit -o noclobber -o nounset

hue=(-level 0%,100%,0.6)
effect=(-filter Gaussian -resize 20% -define filter:sigma=1.5 -resize 500.5%)
font="$(convert -list font | awk "{ a[NR] = \$2 } /family: $(fc-match sans -f "%{family}\n")/ { print a[NR-1]; exit }")"
image="$(mktemp).png"
shot=(import -window root)
desktop=$(command -V wmctrl)
cmd=(i3lock -i "$image")

set -o pipefail
trap 'rm -f "$image"' EXIT

text="Type password to unlock"

command -- "${shot[@]}" "$image"

value=60
color=$(convert "$image" -gravity center -crop 100x100+0+0 +repage -colorspace hsb \
  -resize 1x1 txt:- | awk -F '[%$]' 'NR==2{gsub(",",""); printf "%.0f\n", $(NF-1)}');

if [[ $color -gt $value ]]; then
  bw="black"
  icon="$HOME/.config/i3/lockdark.png"
  param=("--insidecolor=0000001c" "--ringcolor=0000003e" \
      "--linecolor=00000000" "--keyhlcolor=ffffff80" "--ringvercolor=ffffff00" \
      "--separatorcolor=22222260" "--insidevercolor=ffffff1c" \
      "--ringwrongcolor=ffffff55" "--insidewrongcolor=ffffff1c" \
      "--verifcolor=ffffff00" "--wrongcolor=ff000000" "timecolor=ffffff00" \
      "--datecolor=ffffff00" "--layoutcolor=ffffff00")
else
  bw="white"
  icon="$HOME/.config/i3/lock.png"
  param=("--insidecolor=ffffff1c" "--ringcolor=ffffff3e" \
      "--linecolor=ffffff00" "--keyhlcolor=00000080" "--ringvercolor=00000000" \
      "--separatorcolor=22222260" "--insidevercolor=0000001c" \
      "--ringwrongcolor=00000055" "--insidewrongcolor=0000001c" \
      "--verifcolor=00000000" "--wrongcolor=ff000000" "timecolor=00000000" \
      "--datecolor=00000000" "--layoutcolor=00000000")
fi

convert "$image" "${hue[@]}" "${effect[@]}" -font "$font" -pointsize 26 -fill "$bw" -gravity center \
  -annotate +0+160 "$text" "$icon" -gravity center -composite "$image"

${desktop} ${desktop:+-k on}

if ! "${cmd[@]}" "${param[@]}" >/dev/null 2>&1; then
  "${cmd[@]}"
fi

${desktop} ${desktop:+-k off}
