# vim: ft=yaml.ansible
---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: latest
  become: true

- name: Install git Global Ignore File
  ansible.builtin.file:
    src: "{{ role_path }}/files/gitignore"
    dest: "{{ ansible_env.HOME }}/.gitignore"
    state: link

- name: Install git Global Configuration File
  ansible.builtin.file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    state: link
